#!/usr/bin/env python3
"""Test runner for the openspec generator.

This test runs the generator, captures the produced filepath, and asserts
that the file exists and contains required front-matter and sections.

Exit code 0 on success, non-zero on failure.
"""
import os
import re
import shutil
import subprocess
import sys


def run_generator():
    script = os.path.join(os.path.dirname(__file__), "generate_proposal.py")
    title = "Test Generated Proposal"
    prompt = "This is a test generated by automated test_generate.py"
    p = subprocess.run([sys.executable, script, "--title", title, "--prompt", prompt], capture_output=True, text=True)
    if p.returncode != 0:
        print("Generator failed:", p.stderr)
        return None
    path = p.stdout.strip()
    return path


def assert_contains(path: str, patterns):
    with open(path, "r", encoding="utf-8") as f:
        txt = f.read()
    for pat in patterns:
        if not re.search(pat, txt, re.IGNORECASE | re.MULTILINE):
            print(f"Missing pattern in generated file: {pat}")
            return False
    return True


def main():
    path = run_generator()
    if not path:
        print("FAIL: generator did not produce a path")
        return 2
    if not os.path.isfile(path):
        print("FAIL: generated file not found at", path)
        return 3

    patterns = [
        r"^---\s*$",  # front-matter start
        r"id:\s*\d+",  # id present
        r"generated_by:",
        r"# Summary",
        r"## Motivation",
        r"## Specification",
        r"## Tests",
    ]

    ok = assert_contains(path, patterns)
    if not ok:
        print("FAIL: content assertions failed for", path)
        return 4

    print("PASS: generated proposal looks good:", path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
